adding julia image
saturncloud/images pull request #310
Opened 2022-02-15 17:47 UTC by nathanballou

Adds a Julia image called saturnbase-julia containing Julia 1.7.2. This mostly copies saturnbase, but includes additional code to download Julia, link it, and install IJulia for Jupyter integration. 

It attempts to be as lightweight as possible, but there may be additional packages we can remove etc.

The image also contains python 3.9 as an alternative kernel - we might want to remove it.

You install Julia packages using a start script like the following. Perhaps another place for improvement.
```
julia -e 'import Pkg;
Pkg.add("Package1");
Pkg.add("Package2")'
```

2022-02-20 22:43 UTC, nathanballou commented
Added saturn-julia containing the following packages. We can refine over time.
Convex
DataFrames
Dierckx
ExcelReaders
Flux
Gadfly
HDF5
Ipopt
JLD
JuMP
LsqFit
MLBase
NMF
Optim
Plots
ProgressMeter
PyCall
PyPlot
RDatasets
SCS
SQLite
Spectra
Turing

2022-03-03 20:09 UTC, nathanballou commented
"Bio",
"Clustering",
"DataFrames", 
"Distances",
"Flux", 
"HDF5",
"MLBase",
"Optim",
"Plots",
"ProgressMeter",
"PyCall",
"PyPlot",
"RDatasets",
"SCS",
"Statistics",
"SQLite"

2022-03-03 20:27 UTC, forana commented
We aren't planning on building any new versions of `release-2022.01.06`, as far as I know - this should merge into either `release-2022.03.01` or `main`.

2022-03-08 20:15 UTC, jnolis requested changes

2022-03-08 20:15 UTC, jnolis commented on saturn-julia/.env_deps
> +VERSION=2022.01.06-1
I don't think this file is actually used for anything, but the dates are old

2022-03-08 20:15 UTC, jnolis commented on saturn-julia/Makefile
> +		-t narobboo/julia-base:0.06 \
what is narobboo??

2022-03-08 20:15 UTC, jnolis commented on saturn-julia/recipe-template.json
> +        "julia"
Did alex ask for this? I'm surprised that we're adding a supports

2022-03-08 20:15 UTC, jnolis commented on saturnbase-julia/Dockerfile
> +    fix-permissions "${JULIA_PKGDIR}" "${CONDA_DIR}/share/jupyter"
Should you delete the fix-permissions script at the end?

2022-03-14 14:31 UTC, jnolis approved these changes
Love it!

2022-03-14 14:32 UTC, merged